services:
  smartcanopy-website:
    build: .
    container_name: smartcanopy-website
    restart: always
    ports:
      - "29925:80"
    networks:
      - cf-net

networks:
  cf-net:
    external: true
