services:
  smartcanopy-website:
    build: .
    container_name: smartcanopy-website
    restart: always
    ports:
      - "29925:29925"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
